### ISSUE TITLE
Improve color picker

### ISSUE THREAD

**Issue by brianpeiris** [MozillaReality/hubs-editor#14]
Should show a swatch (and maybe hex/rgb/hsl) and only open full color picker on click.

**Comment by tony056** [comment]
What about displaying a color block and opacity at first and show the full picker after clicking on the color block?
Like this photo at the right?
![image](https://user-images.githubusercontent.com/1279214/42531422-c5a6060a-8438-11e8-8af5-d705b3f53da1.png)

**Comment by brianpeiris** [comment]
Sure, opacity might be useful. Though it's not very useful to control opacity for values like `emissiveFactor`, so maybe the option not to show opacity would be good.

**Comment by tony056** [comment]
Ok, I see. Then let's just display the color block and a textfield with hex value first and also remove the alpha from the full color picker. Sounds good?

**Comment by brianpeiris** [comment]
Sounds good!

**Comment by tony056** [comment]
Done. [PR#40](https://github.com/MozillaReality/hubs-editor/pull/40).
