### ISSUE TITLE
You should be able to drag orphaned nodes onto another node.

### ISSUE THREAD

**Issue by brianpeiris** [MozillaReality/hubs-editor#54]
After #52, orphaned nodes are displayed in the hierarchy, but you cannot move or modify them. Perhaps users should be able to move them under valid nodes.

**Comment by tony056** [comment]
Is that ok I only enable children under the missing root since we haven't came up with a solution for the duplicate nodes situation in #57?

**Comment by brianpeiris** [comment]
I'm not sure how this relates to duplicate nodes, but yes, I imagine you should only be able to move the children, not the missing root itself.

**Comment by tony056** [comment]
PR #59
