### ISSUE TITLE
HierarchyPanel - unnamed nodes in the gltf file

### ISSUE THREAD

**Issue by tony056** [MozillaReality/hubs-editor#56]
Currently, we do not deal with unnamed nodes, so the editor looks like this when we open a gltf file with many unnamed nodes. Any suggestion on how to handle unnamed nodes situation? 
![unnamed-nodes](https://user-images.githubusercontent.com/1279214/42784274-8cbcab62-8903-11e8-8566-937e46b5ddd7.JPG)

I'm thinking about applying `[unique_prefix]_x-y-z-...` (x, y, z represents the index and layer the node saved in the gltf file) to unnamed nodes in `SceneLoader.js`.

**Comment by brianpeiris** [comment]
Yup, I think unnamed nodes are a special case of the duplicate nodes problem, so naming them `unamed_0-1-3` makes sense.
