### ISSUE TITLE
Deleting Item Does Page Back

### ISSUE THREAD

**Issue by RianLong** [MozillaReality/hubs-editor#68]
Using the delete key to remove an object prompts the browser to go back a page.
<img width="1670" alt="screen shot 2018-07-23 at 1 12 33 pm" src="https://user-images.githubusercontent.com/6235018/43100401-180d0722-8e7a-11e8-9860-72f886a3aaa6.png">

**Comment by brianpeiris** [comment]
I can't repro this. Is it only a bug on macOS?
